### ISSUE TITLE
Mute says it succeeds, then fails

### ISSUE THREAD

**Issue by ericasberry** [DTVD/rainbowstream#154] opened 2016-01-28 22:27 UTC
Really loving this client, it's just what I've been looking for.  One problem I'm having though, whenever I try to mute a user, it says they are muted, and then immediately says it's failed.  And indeed they are not actually muted.

> [@EricAsberry]: mute @somenoisyuser
> @somenoisyuser is muted.
> Something is wrong, can not mute now :(

I've tried restarting, and also insured the config file is accessible by the user.  Not sure what else to check.  Thanks!

**Comment by Azy8BsKXVko** [comment] 2016-02-09 01:05
This appears to have been caused by a typo in the code. I created a fix, which I'll submit as a pull request shortly.

**Comment by DTVD** [comment] 2016-02-09 05:12
Thanks! This is fixed in v1.3.2.

**Closed by DTVD** 2016-02-09 05:12 UTC
